# Generated by Django 5.1.3 on 2024-11-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_queries_shorturls_delete_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queries',
        ),
        migrations.DeleteModel(
            name='ShortUrls',
        ),
    ]
