# Dockerfile.dev

# Use the production image as the base
FROM personal-website-backend

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONMUTEX=1

# Install debugpy for debugging
RUN pip install debugpy watchdog

# Expose the debugging port
EXPOSE 5678

# Copy the common and development entrypoint scripts
COPY docker_entrypoint_common.sh /app/docker_entrypoint_common.sh
COPY docker_entrypoint_dev.sh /app/docker_entrypoint.sh
RUN chmod +x /app/docker_entrypoint.sh /app/docker_entrypoint_common.sh

# Mount your source code for hot-reloading (optional, see note below)
# This step is typically done at run time with a volume mount, not in the Dockerfile

# Set the entrypoint
ENTRYPOINT ["/app/docker_entrypoint.sh"]
