services:
  backend:
    image: personal-website-backend:latest
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DEBUG: 1
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcp-credentials.json
    volumes:
      - ./.secrets:/app/.secrets:ro  # Mount the .secrets file from the current directory
      - ./docker_entrypoint.sh:/app/docker_entrypoint.sh:ro  # Mount the entrypoint script
    entrypoint: ["/app/docker_entrypoint.sh"]  # Set the entrypoint to the script