# Generated by Django 5.1.3 on 2024-11-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_remove_shorturls_llm_query_shorturls_long_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturls',
            name='short_url',
        ),
        migrations.AddField(
            model_name='shorturls',
            name='url_hash',
            field=models.CharField(default='', max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
