name: Deploy Backend to GCP

on:
  push:
    branches:
      - main
      - backend
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
    # 1. Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # 2. Install Node.js, Docker, and prerequisites with liveness prints
    - name: Install Node.js and Docker
      run: |
        set -x  # Enable verbose logging
        echo "Checking if other package managers are holding the lock..."

        # Check if other package managers are running
        while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do
          echo "Waiting for other package managers to finish..."
          sleep 5
        done

        echo "Package manager lock is free. Proceeding with installation..."

        # Update package list and install apt-utils to avoid debconf warning
        echo "Updating package list and installing apt-utils..."
        sudo apt-get update
        sudo apt-get install -y apt-utils

        echo "Installing necessary prerequisites (apt-transport-https, ca-certificates, curl)..."
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common gnupg

        # Install Node.js (LTS version)
        echo "Installing Node.js..."
        curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt-get install -y nodejs
        echo "Node.js installed."

        # Install Docker
        echo "Installing Docker..."
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update && sudo apt-get install -y docker-ce
        echo "Docker installed."

        # Add current user to Docker group to avoid needing sudo
        echo "Adding current user to Docker group..."
        sudo usermod -aG docker $USER
        newgrp docker

        # Verify installations with periodic feedback
        echo "Verifying versions..."

        echo "Checking Node.js version..."
        if ! node -v; then
          echo -e "\033[0;31mERROR: Node.js is not installed or not available.\033[0m"
          exit 1
        else
          echo -e "\033[0;32mNode.js version: $(node -v)\033[0m"
        fi

        echo "Checking npm version..."
        if ! npm -v; then
          echo -e "\033[0;31mERROR: npm is not installed or not available.\033[0m"
          exit 1
        else
          echo -e "\033[0;32mNPM version: $(npm -v)\033[0m"
        fi

        echo "Checking Docker version..."
        if ! docker --version; then
          echo -e "\033[0;31mERROR: Docker is not installed or not available.\033[0m"
          exit 1
        else
          echo -e "\033[0;32mDocker version: $(docker --version)\033[0m"
        fi

        echo "Checking Docker info..."
        if ! docker info; then
          echo -e "\033[0;31mERROR: Docker info check failed.\033[0m"
          exit 1
        fi
      shell: bash
      timeout-minutes: 60  # Add a 10-minute timeout for the step

    # 3. Install Google Cloud SDK and kubectl with liveness prints
    - name: Install Google Cloud SDK and kubectl
      run: |
        set -x  # Enable verbose logging
        echo "Installing Google Cloud SDK and kubectl..."

        # Add the Google Cloud SDK distribution URI as a package source
        echo "Adding Google Cloud SDK repository..."
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

        # Import the Google Cloud public key
        echo "Importing Google Cloud public key..."
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

        # Update and install the Cloud SDK and kubectl
        echo "Updating package list and installing Google Cloud SDK and kubectl..."
        apt-get update && apt-get install -y google-cloud-sdk kubectl
        echo "Google Cloud SDK and kubectl installed."

        # Verify installations
        echo "Verifying Google Cloud SDK and kubectl versions..."

        echo "Checking Google Cloud SDK version..."
        if ! gcloud --version; then
          echo -e "\033[0;31mERROR: Google Cloud SDK is not installed or not available.\033[0m"
          exit 1
        else
          echo -e "\033[0;32mGoogle Cloud SDK version: $(gcloud --version)\033[0m"
        fi

        echo "Checking kubectl version..."
        if ! kubectl version --client; then
          echo -e "\033[0;31mERROR: kubectl is not installed or not available.\033[0m"
          exit 1
        else
          echo -e "\033[0;32mKubectl version: $(kubectl version --client)\033[0m"
        fi
      shell: bash

    # 4. Cache Docker layers to speed up builds
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # 5. Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # 6. Authenticate with Google Cloud using service account credentials
    - name: Set up GCP Credentials
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        echo "Setting up GCP credentials..."
        echo "$GCP_SA_KEY" | base64 --decode > /tmp/gcp-key-temp.json
        gcloud auth activate-service-account --key-file=/tmp/gcp-key-temp.json
        gcloud config set project $GCP_PROJECT_ID

    # 7. Configure Docker to use GCloud credentials for pushing images
    - name: Configure Docker to use GCloud credentials
      run: |
        echo "Configuring Docker to use GCloud credentials for pushing images..."
        gcloud auth configure-docker gcr.io --quiet

    # 8. Build and push the Docker image to Google Container Registry (GCR)
    - name: Build and push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/personal-website-backend:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    # 9. Update the Docker cache for future builds
    - name: Move cache
      run: |
        echo "Moving Docker cache..."
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    # 10. Deploy the Docker image to Google Cloud Run
    - name: Deploy to Cloud Run
      run: |
        echo "Deploying to Cloud Run..."
        PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}"
        REGION="us-central1"
        SERVICE_NAME="personal-website-backend"
        GCR_IMAGE_NAME="gcr.io/${PROJECT_ID}/personal-website-backend"
        SERVICE_ACCOUNT="personal-website-deployer@${PROJECT_ID}.iam.gserviceaccount.com"

        gcloud run deploy $SERVICE_NAME \
          --image ${GCR_IMAGE_NAME}:latest \
          --project $PROJECT_ID \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="DEBUG=1,GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json" \
          --port=8080 \
          --service-account=$SERVICE_ACCOUNT

    # 11. Print the deployed service URL
    - name: Print Service URL
      run: |
        SERVICE_NAME="personal-website-back
