name: Deploy Backend to GCP

on:
  push:
    branches: 
      - main
      - backend
    paths:
      - 'backend/**'
  # workflow_dispatch:  # This allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Debug GCP Credentials
      run: |
        echo "Length of GCP_SA_KEY: ${#GCP_SA_KEY}"
        echo "First 10 characters of GCP_SA_KEY: ${GCP_SA_KEY:0:10}..."
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    - name: Set up GCP Credentials
      run: |
        mkdir -p backend/creds
        echo '${{ secrets.GCP_SA_KEY }}' | base64 -d > backend/creds/gcp-sa-key.json
        chmod 600 backend/creds/gcp-sa-key.json

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: backend/creds/gcp-sa-key.json
        export_default_credentials: true

    - name: Deploy to GCP
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        cd backend
        chmod +x ./deploy_to_gcp.sh
        ./deploy_to_gcp.sh

    - name: Clean up
      if: always()
      run: rm -f backend/creds/gcp-sa-key.json