name: Deploy Backend to GCP

on:
  push:
    branches: 
      - main
      - backend
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up GCP Credentials
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > backend/creds/gcp-sa-key.json
        chmod 600 backend/creds/gcp-sa-key.json

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: backend/creds/gcp-sa-key.json
        export_default_credentials: true

    - name: Deploy to GCP
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        cd backend
        chmod +x ./deploy_to_gcp.sh
        ./deploy_to_gcp.sh

    - name: Clean up
      if: always()
      run: rm -f backend/creds/gcp-sa-key.json