name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, staging ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Set environment variables
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "REACT_APP_API_URL=${{ secrets.PROD_API_URL }}" >> $GITHUB_ENV
          echo "REACT_APP_ENVIRONMENT=production" >> $GITHUB_ENV
        else
          echo "REACT_APP_API_URL=${{ secrets.STAGING_API_URL }}" >> $GITHUB_ENV
          echo "REACT_APP_ENVIRONMENT=staging" >> $GITHUB_ENV
        fi

    - name: Build
      run: |
        cd frontend
        npm run build
      env:
        REACT_APP_API_URL: ${{ env.REACT_APP_API_URL }}
        REACT_APP_ENVIRONMENT: ${{ env.REACT_APP_ENVIRONMENT }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/build
        destination_dir: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
        force_orphan: false